# Generated by Django 3.1.3 on 2021-01-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('form', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='WiseSaying',
        ),
    ]
