# Generated by Django 3.1.3 on 2021-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xss',
            name='detail',
            field=models.JSONField(max_length=300),
        ),
    ]
